on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy...
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: 22
          script_stop: true
          script: |
            cd /apps/criarideias/front && git pull
